import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ImageLoad from "./imageLoad";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  function onSubmit(e) {
    e.preventDefault();
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} ${inter.className} h-full bg-sky-100  `}
      >
        <div className="flex flex-col h-screen">
          <h2>Crear nuevo POAP</h2>
          <div className=" ">
            <form className="flex flex-col gap-4">
              <label htmlFor="eventName">Nombre </label>
              <input
                type="text"
                placeholder="Nombre del evento"
                id="enventName"
              ></input>
              <label htmlFor="cantidad">Cantidad de POAPS </label>
              <input
                type="number"
                placeholder="Cantidad de poaps"
                id="cantidad"
              ></input>
              <label htmlFor="expiration">Expiración </label>
              <input
                type="date"
                placeholder="Expiracion"
                id="expiration"
              ></input>
              <label htmlFor="decription">Descripción </label>
              <textarea
                type="text"
                placeholder="Descripcion"
                id="decription"
              ></textarea>

              <ImageLoad></ImageLoad>
              <input
                className="border border-teal-300 bg-teal-500 cursor-pointer "
                type="submit"
                value="Enviar"
              ></input>
            </form>
          </div>
          
          <div>
            <form onSubmit={onSubmit} className="flex flex-col gap-4">
              <label htmlFor="deposit">Cantidad de POAPS </label>
              <input
                type="number"
                placeholder="Depositar en relayer"
                id="deposit"
              ></input>
              <input type="submit" value="Depositar MATIC" className="border border-teal-300 bg-teal-500 cursor-pointer "></input>
            </form>
          </div>

          <div className="border border-black h-60">
            <p>GENERATED QR</p>
          </div>

        </div>
      </main>
    </>
  );
}
